import { AsideProvider } from "@/components/context/AsideContext";
import { CartProvider } from "@/components/context/CartContext";
import DynamicAsidePanel from "@/components/DynamicAsidePanel";
import ScrollToTopButton from "@/components/ScrollToTopButton";
import MainFooter from "@/shared/footer/MainFooter";
import MainNavigationBar from "@/shared/navigationBar/MainNavigationBar";
import { Rethink_Sans, Unbounded } from "next/font/google";
import "./globals.css";

const unbounded = Unbounded({
  subsets: ["latin"],
  variable: "--font-marcellus",
  weight: ["400", "600", "700"],
});

const rethinkSans = Rethink_Sans({
  subsets: ["latin"],
  variable: "--font-rethink-sans",
  weight: ["400", "500", "700"],
});

export const metadata = {
  title: "xstore",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${unbounded.variable} ${rethinkSans.variable} antialiased`}
      >
        <CartProvider>
          <AsideProvider>
            <MainNavigationBar />
            {children}
            <DynamicAsidePanel />
          </AsideProvider>
        </CartProvider>

        <MainFooter />
        <ScrollToTopButton />
      </body>
    </html>
  );
}
